CREATE TABLE EMPLOYEE
(
    ID   LONG PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);
CREATE TABLE EMAIL
(  EMAILID LONG PRIMARY KEY AUTO_INCREMENT,
   EMAIL VARCHAR(255),
   ID LONG,
   FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE ADDRESS
(
    ID   LONG PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(255)
);

CREATE TABLE EMPLOYEEADDRESS
(
    EMPLOYEEID   LONG,
    ADDRESSID LONG,
    PRIMARY KEY(EMPLOYEEID, ADDRESSID),
    FOREIGN KEY(EMPLOYEEID) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY(ADDRESSID) REFERENCES ADDRESS(ID)
);


